PhotoShare/Models/Photo.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Azure;
using PhotoShare.Data;

namespace PhotoShare.Models
{
    public class Photo
    {
        // primary key
        public int PhotoId { get; set; }

        public string Description { get; set; } = string.Empty;

        public string Location { get; set; } = string.Empty;

        public string Camera { get; set; } = string.Empty;

        public string ImageFilename { get; set; } = string.Empty;




        // Property for file upload, not mapped in EF
        [NotMapped]
        [Display(Name = "Photograph")]
        public IFormFile? ImageFile { get; set; } // nullable!

        [Display(Name = "Visibility")]
        public bool IsVisible { get; set; } = false;

        [Display(Name = "Date Created")]
        public DateTime CreatedAt { get; set; } = DateTime.Now;

        // Navigation property
        public List<Tag>? Tags { get; set; }  // nullable!!!

        // Foreign key (AspNetUsers table)
        public string ApplicationUserId { get; set; } = string.Empty;

        // Navigation property
        public ApplicationUser? ApplicationUser { get; set; } // nullable!!!

    }
}

PhotoShare/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using NuGet.Versioning;
using PhotoShare.Data;
using PhotoShare.Models;

namespace PhotoShare.Controllers
{
    // only logged in users have access
    [Authorize]
    public class PhotosController : Controller
    {
        private readonly PhotoShareContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        //constructor

        public PhotosController(PhotoShareContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Photos
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);

            var photos = await _context.Photo
            .Where(m => m.ApplicationUserId == userId)
            .ToListAsync();

            return View(photos);
        }

  
        // GET: Photos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Photos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PhotoId,Description,Location,Camera,ImageFile,IsVisible")] Photo photo)
        {
            photo.CreatedAt = DateTime.Now;
            // rename the uploaded file to a guid (unique filename). Set before photo saved in database.
            photo.ImageFilename = Guid.NewGuid().ToString() + Path.GetExtension(photo.ImageFile?.FileName);

            //Set the user id of the person logged in 
            photo.ApplicationUserId = _userManager.GetUserId(User);


            if (ModelState.IsValid)
            {
                //save the photo in database
                _context.Add(photo);
                await _context.SaveChangesAsync();

                // Save the uploaded file after the photo is saved in the database.
                if (photo.ImageFile != null)
                {
                    string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "photos", photo.ImageFilename);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await photo.ImageFile.CopyToAsync(fileStream);
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            return View(photo);
        }

        // GET: Photos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userId = _userManager.GetUserId(User);

            var photo = await _context.Photo
                .Include(m => m.Tags)
                .Where(m => m.ApplicationUserId == userId)
                .FirstOrDefaultAsync(m => m.PhotoId == id);

            if (photo == null)
            {
                return NotFound();
            }
            return View(photo);
        }

        // POST: Photos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PhotoId,Description,Location,Camera,ImageFilename,IsVisible,CreatedAt,ApplicationUserId")] Photo photo)
        {
            if (id != photo.PhotoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(photo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PhotoExists(photo.PhotoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(photo);
        }

        // GET: Photos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userId = _userManager.GetUserId(User);

            var photo = await _context.Photo
                .Where(m => m.ApplicationUserId == userId)
                .FirstOrDefaultAsync(m => m.PhotoId == id);

            if (photo == null)
            {
                return NotFound();
            }

            return View(photo);
        }

        // POST: Photos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userId = _userManager.GetUserId(User);
            var photo = await _context.Photo
                 .Where(m => m.ApplicationUserId == userId)
                .FirstOrDefaultAsync(m => m.PhotoId == id);

            if (photo == null)
            {
                return NotFound();
            } 
            else
            {
                _context.Photo.Remove(photo);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PhotoExists(int id)
        {
            return _context.Photo.Any(e => e.PhotoId == id);
        }
    }
}

PhotoShare/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PhotoShare.Data;
using PhotoShare.Models;

namespace PhotoShare.Controllers
{
    // only logged in users have access
    [Authorize]
    public class TagsController : Controller
    {
        private readonly PhotoShareContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public TagsController(PhotoShareContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }
        //DELETED THESE ACTIONS
        // GET: Tags
        // GET: Tags/Details/5
        // GET: Tags/Edit/5
        // POST: Tags/Edit/5
        // POST: Tags/Delete/5


        // GET: Tags/Create
        public async Task<IActionResult> CreateAsync(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var userId = _userManager.GetUserId(User);
            var photo = await _context.Photo
                 .Where(m => m.ApplicationUserId == userId)
                .FirstOrDefaultAsync(m => m.PhotoId == id);

            if (photo == null)
            {
                return NotFound();
            }


            ViewData["PhotoId"] = id;

            return View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TagId,Name,PhotoId")] Tag tag)
        {
            //
            // TODO: embed the user ID in the form and validate 
            //

            if (ModelState.IsValid)
            {
                _context.Add(tag);
                await _context.SaveChangesAsync();

                //redirect to /Photos/Edit/5
                return RedirectToAction("Edit", "Photos", new { id = tag.PhotoId });
            }
            ViewData["PhotoId"] = new SelectList(_context.Photo, "PhotoId", "PhotoId", tag.PhotoId);
            return View(tag);
        }



        // GET: Tags/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            //
            // TODO: verify the the user ID for Photo matches the logged in user 
            //

            // id is the tag id
            if (id == null)
            {
                return NotFound();
            }

            var tag = await _context.Tag.FirstOrDefaultAsync(m => m.TagId == id);

            if (tag == null)
            {
                return NotFound();
            }

            // set the photo id to pass to return to the Photo Details page
            var photoId = tag.PhotoId;

            // Remove the tag
            _context.Tag.Remove(tag);
            await _context.SaveChangesAsync();

            return RedirectToAction("Edit", "Photos", new { id = photoId });
        }


    }
}

PhotoShare/Views/Photos/Create.cshtml
@model PhotoShare.Models.Photo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Photo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Camera" class="control-label"></label>
                <input asp-for="Camera" class="form-control" />
                <span asp-validation-for="Camera" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="ImageFile" class="form-label"></label>
                <input type="file" asp-for="ImageFile" class="form-control" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            @* <div class="form-group"> *@
            @*     <label asp-for="ImageFilename" class="control-label"></label> *@
            @*     <input asp-for="ImageFilename" class="form-control" /> *@
            @*     <span asp-validation-for="ImageFilename" class="text-danger"></span> *@
            @* </div> *@
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsVisible" /> @Html.DisplayNameFor(model => model.IsVisible)
                </label>
            </div>
            @* <div class="form-group"> *@
            @*     <label asp-for="CreatedAt" class="control-label"></label> *@
            @*     <input asp-for="CreatedAt" class="form-control" /> *@
            @*     <span asp-validation-for="CreatedAt" class="text-danger"></span> *@
            @* </div> *@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PhotoShare/Views/Photos/Delete.cshtml
@model PhotoShare.Models.Photo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>

    <div class="mb-3 w-50">
        <img src="/photos/@Model.ImageFilename" alt="@Model.Description" class="img-fluid" />
    </div>


    <form asp-action="Delete">
        <input type="hidden" asp-for="PhotoId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PhotoShare/Views/Photos/Edit.cshtml
@model PhotoShare.Models.Photo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Photo</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PhotoId" />
            <input type="hidden" asp-for="ImageFilename" />
            <input type="hidden" asp-for="CreatedAt" />
            <input type="hidden" asp-for="ApplicationUserId" />

            <div class="mb-3 w-50">
                <img src="/photos/@Model.ImageFilename" alt="@Model.Description" class="img-fluid" />
            </div>

            <div class="mb-3">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Camera" class="control-label"></label>
                <input asp-for="Camera" class="form-control" />
                <span asp-validation-for="Camera" class="text-danger"></span>
            </div>
            @* <div class="mb-3"> *@
            @*     <label asp-for="ImageFilename" class="control-label"></label> *@
            @*     <input asp-for="ImageFilename" class="form-control" /> *@
            @*     <span asp-validation-for="ImageFilename" class="text-danger"></span> *@
            @* </div> *@
            <div class="mb-3 form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsVisible" /> @Html.DisplayNameFor(model => model.IsVisible)
                </label>
            </div>
            <div class="mb-3">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" readonly />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
            <div class="mb-3">
                <a asp-action="Create" asp-controller="Tags" asp-route-id="@Model.PhotoId" class="btn btn-secondary me-2">Add tag</a>

                @if (Model.Tags != null)
                {
                    foreach (var tag in Model.Tags)
                    {
                        <span class="pe-2">@tag.Name <a asp-controller="Tags" asp-action="Delete" asp-route-id="@tag.TagId">x</a> </span>
                    }
                }


            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PhotoShare/Views/Photos/Index.cshtml
@model IEnumerable<PhotoShare.Models.Photo>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
        <th>
            Photograph
        </th>


            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Camera)
            </th>
            @* <th> *@
            @*     @Html.DisplayNameFor(model => model.ImageFilename) *@
            @* </th> *@
            <th>
                @Html.DisplayNameFor(model => model.IsVisible)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <img src="/photos/@item.ImageFilename" alt="@item.Description" class="thumbnail" />
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Camera)
            </td>
            @* <td> *@
            @*     @Html.DisplayFor(modelItem => item.ImageFilename) *@
            @* </td> *@
            <td>
                @Html.DisplayFor(modelItem => item.IsVisible)
            </td>
            <td>
              @item.CreatedAt.ToString("MMM d, yyyy")
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.PhotoId" class="text-secondary"><i class="fa-regular fa-pen-to-square"></i></a> |
                @* <a asp-action="Details" asp-route-id="@item.PhotoId">Details</a> | *@
                    <a asp-action="Delete" asp-route-id="@item.PhotoId" class="text-secondary"><i class="fa-solid fa-trash"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>